server:
  port: 8001
spring:
  application:
    name: cloud_payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql:///base_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: yfhasd

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud_project.payment.entities    # 所有Entity别名类所在包
